// Using CommonJS for compatibility with the Node.js script.
const generateUniqueBlogPosts = (count) => {
  return new Promise((resolve) => {
    console.log(`Generating ${count} mock blog posts...`);
    const newPosts = [];
    for (let i = 0; i < count; i++) {
      const newId = `post${79 + i}`; // Start from post 79
      newPosts.push({
        id: newId,
        titleKey: `AI-Generated Title for ${newId}`,
        summaryKey: `This is a unique, AI-generated summary for ${newId}. It discusses modern trends in branding and design.`,
        contentKey: `This is the full content for ${newId}. It would be several paragraphs long and generated by a large language model to be completely unique and engaging for the reader. The topic would be relevant to branding, 3D design, or digital marketing in the Moroccan context.`,
        authorKey: 'BrandHUB AI',
        dateKey: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
        imageUrl: `https://picsum.photos/seed/${newId}/600/400`,
      });
    }
    // Simulate a network delay for the generation process
    setTimeout(() => {
      console.log('Mock generation complete.');
      resolve(newPosts);
    }, 2000);
  });
};

module.exports = { generateUniqueBlogPosts };
